create index if not exists idx_profiles_recruiter_code on profiles(recruiter_code);
create index if not exists idx_profiles_workflow_status on profiles(workflow_status);
create index if not exists idx_profiles_created_at on profiles(created_at);
create index if not exists idx_profiles_next_followup_at on profiles(next_followup_at);
create index if not exists idx_submissions_recruiter_code on submissions(recruiter_code);
create index if not exists idx_notifications_user_code on notifications(user_code);
create index if not exists idx_notifications_user_code_is_read on notifications(user_code, is_read);
create index if not exists idx_tasks_assigned_to on tasks(assigned_to);
create index if not exists idx_interviews_recruiter_code on interviews(recruiter_code);
create index if not exists idx_users_user_code on users(user_code);
