create table if not exists users (
  user_id text primary key,
  username text unique not null,
  password text not null,
  full_name text,
  designation text,
  role text,
  recruiter_code text,
  is_active text default '1',
  theme_name text,
  updated_at text
);

create table if not exists candidates (
  candidate_id text primary key,
  call_connected text,
  looking_for_job text,
  full_name text,
  phone text,
  qualification text,
  location text,
  preferred_location text,
  qualification_level text,
  total_experience text,
  relevant_experience text,
  in_hand_salary text,
  ctc_monthly text,
  career_gap text,
  documents_availability text,
  communication_skill text,
  relevant_experience_range text,
  relevant_in_hand_range text,
  submission_date text,
  process text,
  recruiter_code text,
  recruiter_name text,
  recruiter_designation text,
  status text,
  all_details_sent text,
  interview_availability text,
  interview_reschedule_date text,
  approval_status text,
  approval_requested_at text,
  approved_at text,
  approved_by_name text,
  is_duplicate text,
  notes text,
  resume_filename text,
  recording_filename text,
  created_at text,
  updated_at text,
  experience text
);

create table if not exists tasks (
  task_id text primary key,
  title text,
  description text,
  assigned_to_user_id text,
  assigned_to_name text,
  assigned_by_user_id text,
  assigned_by_name text,
  status text,
  priority text,
  due_date text,
  created_at text,
  updated_at text
);

create table if not exists notifications (
  notification_id text primary key,
  user_id text,
  title text,
  message text,
  category text,
  status text,
  metadata text,
  created_at text
);

create table if not exists jd_master (
  jd_id text primary key,
  job_title text,
  company text,
  location text,
  experience text,
  salary text,
  pdf_url text,
  jd_status text,
  notes text,
  created_at text
);

create table if not exists settings (
  setting_key text primary key,
  setting_value text,
  notes text,
  "Instructions" text
);

create table if not exists notes (
  id bigint generated by default as identity primary key,
  candidate_id text,
  username text,
  note_type text,
  body text,
  created_at text
);

create table if not exists messages (
  id bigint generated by default as identity primary key,
  sender_username text,
  recipient_username text,
  body text,
  created_at text
);

create table if not exists interviews (
  interview_id text primary key,
  candidate_id text,
  jd_id text,
  stage text,
  scheduled_at text,
  status text,
  created_at text
);

create table if not exists submissions (
  submission_id text primary key,
  candidate_id text,
  jd_id text,
  recruiter_code text,
  status text,
  approval_status text,
  decision_note text,
  approval_requested_at text,
  approved_by_name text,
  approved_at text,
  approval_rescheduled_at text,
  submitted_at text
);

create table if not exists active_sessions (
  username text primary key,
  session_token text,
  ip_address text,
  user_agent text,
  updated_at text
);

create table if not exists presence (
  user_id text primary key,
  last_seen_at text,
  last_page text,
  is_on_break text,
  break_reason text,
  break_started_at text,
  break_expected_end_at text,
  total_break_minutes text,
  locked text,
  last_call_dial_at text,
  last_call_candidate_id text,
  last_call_alert_sent_at text,
  meeting_joined text,
  meeting_joined_at text,
  screen_sharing text,
  screen_frame_url text,
  last_screen_frame_at text,
  work_started_at text,
  total_work_minutes text
);

create table if not exists unlock_requests (
  request_id text primary key,
  user_id text,
  status text,
  reason text,
  requested_at text,
  approved_by_user_id text,
  approved_by_name text,
  approved_at text
);

create table if not exists activity_log (
  activity_id text primary key,
  user_id text,
  username text,
  action_type text,
  candidate_id text,
  metadata text,
  created_at text
);


create table if not exists scheduled_reports (
  report_id text primary key,
  user_id text,
  title text,
  report_type text,
  filters_json text,
  file_format text,
  frequency_minutes text,
  status text,
  next_run_at text,
  last_run_at text,
  last_file_name text,
  created_at text
);

create table if not exists aaria_queue (
  task_id text primary key,
  user_id text,
  serial_hint text,
  command_text text,
  status text,
  result_text text,
  created_at text,
  updated_at text
);

alter table jd_master add column if not exists pdf_url text;
alter table jd_master add column if not exists jd_status text;
