create table if not exists users (
  user_id text primary key,
  username text unique not null,
  password text not null,
  full_name text,
  designation text,
  role text,
  recruiter_code text,
  is_active text default '1',
  theme_name text default 'corporate-dark',
  updated_at timestamptz default now()
);

create table if not exists candidates (
  candidate_id text primary key,
  call_connected text,
  looking_for_job text,
  full_name text,
  phone text,
  qualification text,
  location text,
  preferred_location text,
  qualification_level text,
  total_experience text,
  relevant_experience text,
  in_hand_salary text,
  ctc_monthly text,
  career_gap text,
  documents_availability text,
  communication_skill text,
  relevant_experience_range text,
  relevant_in_hand_range text,
  submission_date text,
  process text,
  recruiter_code text,
  recruiter_name text,
  recruiter_designation text,
  status text,
  all_details_sent text,
  interview_availability text,
  interview_reschedule_date text,
  approval_status text,
  approval_requested_at text,
  approved_at text,
  approved_by_name text,
  is_duplicate text,
  notes text,
  resume_filename text,
  recording_filename text,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  experience text
);

create table if not exists tasks (
  task_id text primary key,
  title text,
  description text,
  assigned_to_user_id text,
  assigned_to_name text,
  assigned_by_user_id text,
  assigned_by_name text,
  status text,
  priority text,
  due_date text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists notifications (
  notification_id text primary key,
  user_id text,
  title text,
  message text,
  category text,
  status text,
  metadata text,
  created_at timestamptz default now()
);

create table if not exists jd_master (
  jd_id text primary key,
  job_title text,
  company text,
  location text,
  experience text,
  salary text,
  pdf_url text,
  jd_status text,
  notes text,
  created_at timestamptz default now()
);

create table if not exists settings (
  setting_key text primary key,
  setting_value text,
  notes text,
  "Instructions" text
);

create table if not exists notes (
  id bigint generated by default as identity primary key,
  candidate_id text,
  username text,
  note_type text,
  body text,
  created_at timestamptz default now()
);

create table if not exists interviews (
  interview_id text primary key,
  candidate_id text,
  jd_id text,
  stage text,
  scheduled_at text,
  status text,
  created_at timestamptz default now()
);

create table if not exists submissions (
  submission_id text primary key,
  candidate_id text,
  jd_id text,
  recruiter_code text,
  status text,
  approval_status text,
  decision_note text,
  approval_requested_at text,
  approved_by_name text,
  approved_at text,
  approval_rescheduled_at text,
  submitted_at timestamptz default now()
);

create table if not exists activity_log (
  activity_id text primary key,
  user_id text,
  username text,
  action_type text,
  candidate_id text,
  metadata text,
  created_at timestamptz default now()
);

create index if not exists idx_users_username on users(username);
create index if not exists idx_users_role on users(role);
create index if not exists idx_candidates_recruiter_code on candidates(recruiter_code);
create index if not exists idx_candidates_status on candidates(status);
create index if not exists idx_candidates_updated_at on candidates(updated_at desc);
create index if not exists idx_candidates_phone on candidates(phone);
create index if not exists idx_tasks_assigned_to on tasks(assigned_to_user_id);
create index if not exists idx_tasks_status on tasks(status);
create index if not exists idx_notifications_user_status on notifications(user_id, status);
create index if not exists idx_interviews_candidate on interviews(candidate_id);
create index if not exists idx_submissions_candidate on submissions(candidate_id);
create index if not exists idx_submissions_recruiter on submissions(recruiter_code);
create index if not exists idx_notes_candidate on notes(candidate_id);
create index if not exists idx_activity_user_created on activity_log(user_id, created_at desc);
